 import type { Metadata } from "next";
import { Inter, Poppins, Roboto } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";

const inter = Inter({
 subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
   

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider afterSignOutUrl={"/"} >
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
